### ISSUE TITLE
Trying to run examples.ipynb on Colab - serializing/multiprocessing issues

### ISSUE THREAD

**Issue by MeilinaR** [kevinid/molecule_generator#11]
Hi! Thanks for providing the source code. I've been trying to get the mx_net implementation to work on an M1 Macbook Pro on Google Colab, since there were quite some issues with the MXNet + Cuda integration locally. I've made the neccesary changes where needed, adapted the imports of the files, but when trying to run the training code, it gives the following error in Colab:

!python3 train.py scaffold /content/molecule_generator

Traceback (most recent call last):
  File "/content/molecule_generator/train.py", line 535, in <module>
    _engine(**params)
  File "/content/molecule_generator/train.py", line 146, in _engine
    inputs = [next(it_train) for _ in range(len(gpu_ids))]
  File "/content/molecule_generator/train.py", line 146, in <listcomp>
    inputs = [next(it_train) for _ in range(len(gpu_ids))]
  File "/usr/local/lib/python3.10/dist-packages/mxnet/gluon/data/dataloader.py", line 689, in __iter__
    for item in t:
  File "/usr/local/lib/python3.10/dist-packages/mxnet/gluon/data/dataloader.py", line 484, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 643, in __reduce__
    raise NotImplementedError(
NotImplementedError: pool objects cannot be passed between processes or pickled

I was wondering if anyone else had a similar error, and whether someone manages to fix this one.

**Comment by AsyaOrlova** [comment]
@MeilinaR did you manage to solve it? I'm facing the same problem

**Comment by MeilinaR** [comment]
@AsyaOrlova Hi Asya, I was unfortunately not able to fix it!

**Comment by AsyaOrlova** [comment]
@MeilinaR UPD: I fixed it by removing “num_workers” parameter from MolRNNLoader, MolLoader and CMolRNNLoader in train script. Hope it helps!

**Comment by MeilinaR** [comment]
@AsyaOrlova Thanks, that helped :) Did you also happen to encounter the error that Colab can't detect the GPU with MXnet for some reason?

**Comment by AsyaOrlova** [comment]
@MeilinaR I ran scripts locally, so I can’t help with Colab unfortunately
